export default function Head() {
  return (
    <>
      <title>Landing Page | CleanMyVin</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta name="verification" content="00a03ec6533ca7f5c644d198d815329c" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
