export default function Head() {
  return (
    <>
      <title>Landing Page | CleanMyVin</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta
        name="google-site-verification"
        content="XCrt0xYn-HvSVSFD-Nli_Xwopd0win1VZ2iaseOpeNo"
      />
      <meta name="description" content="Generated by create next app" />
      <meta name="verification" content="00a03ec6533ca7f5c644d198d815329c" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
